version: 0.2

phases:
    build:
        commands:
            - echo "compile core" 
            - npm run build-core
            - echo "run tests"
            - npm run test-all
            - echo "publish to npm -not yet implemented"
    post_build:
        commands: 
            - echo "update version -not yet implemented"