version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 12
        commands: 
            - echo "get emsdk"
            - cd ..
            - git clone https://github.com/emscripten-core/emsdk.git
            - cd emsdk && ./emsdk install latest && ./emsdk activate latest
            - CURDIR=$(pwd)
            - PATH="${PATH}:${CURDIR}:${CURDIR}/upstream/emscripten:${CURDIR}/node/12.9.1_64bit/bin"
            - export PATH
            - cd ..
            - cd barnes-hut-tree-builder
    pre_build:
        commands: 
            - npm i
    build:
        commands:
            - echo "compile core" 
            - npm run build-core
            - echo "run tests"
            - npm test
            - if [ ! -d "~/.npmrc" ]; then touch ~/.npmrc; fi 
            - echo "//registry.npmjs.org/:_authToken=${npm-token}" >> ~/.npmrc
            - cat ~/.npmrc
            - npm publish
    post_build:
        commands: 
            - echo "update version -not yet implemented"