version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 12
        commands: 
            - echo "checkout development"
            - git config --global credential.helper '!aws codecommit credential-helper $@'
            - git config --global credential.UseHttpPath true
            - git fetch
            - git checkout development
            - git remote
            - echo "get emsdk"
            - cd ..
            - git clone https://github.com/emscripten-core/emsdk.git
            - cd emsdk && ./emsdk install latest && ./emsdk activate latest
            - CURDIR=$(pwd)
            - PATH="${PATH}:${CURDIR}:${CURDIR}/upstream/emscripten:${CURDIR}/node/12.9.1_64bit/bin"
            - export PATH
            - cd ..
            - cd barnes-hut-tree-builder
    pre_build:
        commands: 
            - npm i
    build:
        commands:
            - echo "compile core" 
            - npm run build-core
            - echo "run tests"
            - npm test
            - echo "merge to master"
            - git status
            - git log --graph --oneline
            - git checkout master
            - git merge development
            - echo "increment release version"
            - npm version -m "Release version"
            - git push
            - echo "build"
            - npm run build
            - echo "publish"
            - if [ ! -d "~/.npmrc" ]; then touch ~/.npmrc; fi 
            - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
            - npm publish
    post_build:
        commands: 
            - echo "merge back to development"
            - git checkout development
            - git merge master
            - git push